version: "3"
services:
  postgres:
      image: postgres:10
      container_name: pg_banlist
      ports:
         - 5432:5432
      environment:
         POSTGRES_DB: banlist
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: U29ta2lkMDU4ODQ4Mzkx
      volumes:
       - ./postgres-data:/var/lib/postgresql/data
       - ./postgresql.conf:/etc/postgresql/postgresql.conf
      restart: always
  pgadmin:
      image: dpage/pgadmin4:3.6
      container_name: pgadmin_banlist
      ports:
       - 7799:80
      volumes:
       - ./pgadmin:/var/lib/pgadmin/storage
      environment:
       PGADMIN_DEFAULT_EMAIL: postgres
       PGADMIN_DEFAULT_PASSWORD: U29ta2lkMDU4ODQ4Mzkx
      restart: always
